### PR TITLE
Code  review request

### PR DESCRIPTION
**Pull request by abdellani**

### CODE REVIEW

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Comment by Torres-ssf** [comment]
### Good job team 👏
You made a great work on your framework. But some features required for Microverse guidelines are missing. We need to implement then:

- [x] Microverse guidelines require that your framework contain at least ten different classes to set the background and text colors of an element

- [x] Your framework should have separate classes for border top, bottom, left, right, all border. The border should span from 0 to 1rem. The border should have classes for making box round

Please kindly make these changes and submit for code review again

**Comment by Oghenebrume50** [comment]
Hi team, good work so far, but I think you guys missed something, currently there is no way to make a box round in your framework, this should be done through your borders, please fix that,  and resubmit for review

**Comment by Oghenebrume50** [comment]
Nice work team :+1: this is perfect, you can merge and move on. Good luck

**Pull request merged**
